version: '3.8'

services:
  lancador:
    container_name: lancador-faturas
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      # Monta as pastas persistentes do host para o local esperado pela aplicação
      - ./resources:/home/node/.lancadorDeFaturaAutomatico/resources
      - ./faturas:/home/node/.lancadorDeFaturaAutomatico/faturas
    env_file:
      - .env
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
